name       : accounts-qml-module
version    : 0.7
release    : 1
source     :
    - git|https://gitlab.com/accounts-sso/accounts-qml-module.git : VERSION_0.7
license    : LGPL-2.1-only
component  : programming
summary    : QML bindings for libaccounts-qt + libsignon-qt
description: |
    This QML module provides an API to manage the user's online accounts and get their authentication data.
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(libsignon-qt5)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make INSTALL_ROOT="$installdir" install_subtargets
